//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatsProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessuars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accessuars()
        {
            this.DeliveryDetails = new HashSet<DeliveryDetails>();
            this.Fits = new HashSet<Fits>();
        }
    
        public int AccessuarId { get; set; }
        public string Title { get; set; }
        public string AccessDescription { get; set; }
        public decimal Price { get; set; }
        public decimal VAT { get; set; }
        public int Inventory { get; set; }
        public int OrderLevel { get; set; }
        public int OrderBatch { get; set; }
        public int PartnerId { get; set; }
    
        public virtual Partners Partners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryDetails> DeliveryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fits> Fits { get; set; }
    }
}
