//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatsProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boats()
        {
            this.Fits = new HashSet<Fits>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int BoatId { get; set; }
        public string Title { get; set; }
        public int BoatTypeId { get; set; }
        public int RowersAmount { get; set; }
        public bool Mast { get; set; }
        public int ColorId { get; set; }
        public int WoodTypeId { get; set; }
        public decimal BasePrice { get; set; }
        public decimal VAT { get; set; }
    
        public virtual BoatTypes BoatTypes { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual WoodTypes WoodTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fits> Fits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
