//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatsProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.Invoices = new HashSet<Invoices>();
        }
    
        public int ContractId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal DepositPayed { get; set; }
        public int OrderId { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal TotalPriceInclVAT { get; set; }
        public int ProductionProcessId { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual ProductionProcesses ProductionProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoices> Invoices { get; set; }
    }
}
